# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: PhaseMessage.proto
# Protobuf Python Version: 5.29.0-rc1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '-rc1',
    'PhaseMessage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12PhaseMessage.proto\"\'\n\x07Phase1A\x12\r\n\x05\x63_rnd\x18\x01 \x01(\x05\x12\r\n\x05phase\x18\x02 \x01(\t\"C\n\x07Phase1B\x12\x0b\n\x03rnd\x18\x01 \x01(\x05\x12\r\n\x05v_rnd\x18\x02 \x01(\x05\x12\r\n\x05v_val\x18\x03 \x01(\t\x12\r\n\x05phase\x18\x04 \x01(\t\"6\n\x07Phase2A\x12\r\n\x05\x63_rnd\x18\x01 \x01(\x05\x12\r\n\x05\x63_val\x18\x02 \x01(\t\x12\r\n\x05phase\x18\x03 \x01(\t\"6\n\x07Phase2B\x12\r\n\x05v_rnd\x18\x01 \x01(\x05\x12\r\n\x05v_val\x18\x02 \x01(\t\x12\r\n\x05phase\x18\x03 \x01(\t\"&\n\x06\x44\x65\x63ide\x12\r\n\x05v_val\x18\x01 \x01(\t\x12\r\n\x05phase\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PhaseMessage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PHASE1A']._serialized_start=22
  _globals['_PHASE1A']._serialized_end=61
  _globals['_PHASE1B']._serialized_start=63
  _globals['_PHASE1B']._serialized_end=130
  _globals['_PHASE2A']._serialized_start=132
  _globals['_PHASE2A']._serialized_end=186
  _globals['_PHASE2B']._serialized_start=188
  _globals['_PHASE2B']._serialized_end=242
  _globals['_DECIDE']._serialized_start=244
  _globals['_DECIDE']._serialized_end=282
# @@protoc_insertion_point(module_scope)
